// ionic/src/pages/Home.tsx
import { IonContent, IonHeader, IonPage, IonTitle, IonToolbar, IonButton, IonIcon } from '@ionic/react';
import React, { useEffect, useState } from 'react';
import { shareSocialOutline } from 'ionicons/icons';

import { Plugins, DeviceInfo } from '@capacitor/core';

import './Home.css';

const Home: React.FC = () => {
  const [deviceInfo, setDeviceInfo] = useState<DeviceInfo | null>(null);

  const shareTweet = async () => {
    const { Share } = Plugins;

    const share = await Share.share({
      title: 'Share Capacitor',
      text: 'I deployed an Ionic React web app as a native mobile app using @capacitorjs in minutes!',
      url: 'https://capacitorjs.com',
    });
  }

  useEffect(() => {
    const getDeviceInfo = async () => {
      const { Device } = Plugins;

      setDeviceInfo(await Device.getInfo());
    };

    getDeviceInfo();
  }, []);

  return (
    <IonPage>
      <IonHeader>
        <IonToolbar>
          <IonTitle>Capacitor Example</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent>
        <IonHeader collapse="condense">
          <IonToolbar>
            <IonTitle size="large">Capacitor Ionic Example</IonTitle>
          </IonToolbar>
        </IonHeader>
        <IonButton onClick={() => shareTweet()}>
          <IonIcon slot="start" icon={shareSocialOutline} />
          Share This
        </IonButton>
        <div className="ion-padding">
          <h2>Device Info:</h2>
          <pre>
          {deviceInfo ? (
            JSON.stringify(deviceInfo, null, 2)
          ) : null}
          </pre>
        </div>
      </IonContent>
    </IonPage>
  );
};

export default Home;

// vuejs-vuetify/src/views/Home.vue
<template>
  <div>
    <v-app-bar>
      <v-icon style="margin-right: 12px;">{{ icons.lightning }}</v-icon>
      <v-toolbar-title>Capacitor Example</v-toolbar-title>
    </v-app-bar>
    <v-main class="content-padding content-centered">
      <v-btn color="primary" v-on:click="shareThis()">
        <v-icon left>{{ icons.share }}</v-icon> Share This
      </v-btn>
      <DeviceInfoCard />
    </v-main>
  </div>
</template>

<script lang="ts">
// @ is an alias to /src
import { mdiShareVariant, mdiLightningBoltOutline } from "@mdi/js";
import { Vue, Component } from "vue-property-decorator";
import DeviceInfoCard from "@/components/DeviceInfoCard.vue";

@Component({ components: { DeviceInfoCard } })
export default class Home extends Vue {
  icons: { [iconKey: string]: unknown } = {
    share: mdiShareVariant,
    lightning: mdiLightningBoltOutline
  };

  constructor() {
    super();
  }

  async shareThis() {
    try {
      await this.$capacitorPlugins.Share.share({
        title: "Share Capacitor",
        text:
          "I deployed an Ionic React web app as a native mobile app using @capacitorjs in minutes!",
        url: "https://capacitorjs.com"
      });
    } catch (e) {
      console.error(e);
    }
  }
}
</script>

<style lang="scss">
.content-padding {
  padding: 10px !important;
}
.content-centered {
  text-align: center;
}
</style>
