// ionic/src/pages/Home.tsx
import { IonContent, IonHeader, IonPage, IonTitle, IonToolbar, IonButton, IonIcon } from '@ionic/react';
import React, { useEffect, useState } from 'react';
import { shareSocialOutline } from 'ionicons/icons';

import { Plugins, DeviceInfo } from '@capacitor/core';

import './Home.css';

const Home: React.FC = () => {
  const [deviceInfo, setDeviceInfo] = useState<DeviceInfo | null>(null);

  const shareTweet = async () => {
    const { Share } = Plugins;

    const share = await Share.share({
      title: 'Share Capacitor',
      text: 'I deployed an Ionic React web app as a native mobile app using @capacitorjs in minutes!',
      url: 'https://capacitorjs.com',
    });
  }

  useEffect(() => {
    const getDeviceInfo = async () => {
      const { Device } = Plugins;

      setDeviceInfo(await Device.getInfo());
    };

    getDeviceInfo();
  }, []);

  return (
    <IonPage>
      <IonHeader>
        <IonToolbar>
          <IonTitle>Capacitor Example</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent>
        <IonHeader collapse="condense">
          <IonToolbar>
            <IonTitle size="large">Capacitor Ionic Example</IonTitle>
          </IonToolbar>
        </IonHeader>
        <IonButton onClick={() => shareTweet()}>
          <IonIcon slot="start" icon={shareSocialOutline} />
          Share This
        </IonButton>
        <div className="ion-padding">
          <h2>Device Info:</h2>
          <pre>
          {deviceInfo ? (
            JSON.stringify(deviceInfo, null, 2)
          ) : null}
          </pre>
        </div>
      </IonContent>
    </IonPage>
  );
};

export default Home;

// svelte-framework7/src/pages/home.svelte
<Page name="home">
  <!-- Top Navbar -->
  <Navbar large sliding={false}>
    <NavTitle sliding>Capacitor 💙 F7</NavTitle>
    <NavTitleLarge>Capacitor 💙 F7</NavTitleLarge>
  </Navbar>
  <!-- Page content -->
  <Block>
    <Button large raised fill iconF7="arrow_up_left_square" iconSize="21" on:click={shareThis}>
      Share This
    </Button>
  </Block>
  <BlockTitle>Device Info</BlockTitle>
  <Block inset strong style="word-wrap: break-word">
    <pre style="word-wrap: break-word; white-space: pre-wrap;">{deviceInfo}</pre>
  </Block>
</Page>
<script>
  import {
    Page,
    Navbar,
    NavTitle,
    NavTitleLarge,
    Block,
    Button,
    BlockTitle
  } from 'framework7-svelte';

  import {Plugins} from '@capacitor/core';

  let deviceInfo = '';

  async function getDeviceInfo() {
    try {
       const { Device } = Plugins
      deviceInfo = JSON.stringify(await Device.getInfo() , null, 2)
    } catch(e) {
      console.error(e);
    }
  }

  async function shareThis() {
    try {
      await Plugins.Share.share({
        title: "Share Capacitor",
        text:
          "I deployed an Svelte + Framework7 web app as a native mobile app using @capacitorjs in minutes!",
        url: "https://capacitorjs.com"
      });
    } catch (e) {
      console.error(e);
    }
  }

  getDeviceInfo();

</script>
